[package]
name = "cqlsh"
version = "0.1.4"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
scylla = "0.4"
tokio = { version = "1.17.0", features = ["full"] }
text_io = "0.1"

[profile.release]
lto = true
debug = false
codegen-units = 1
panic = "abort"
