[package]
name = "cqlsh"
version = "0.1.7"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
scylla = "0.8"
tokio = { version = "1.19.2", features = ["full"] }
text_io = "0.1"

[profile.release]
lto = true
debug = false
codegen-units = 1
panic = "abort"
